import jsPDF from "jspdf";
import type { DatasetProfile } from "./profiler";

export function exportReportPDF(opts: {
  profile: DatasetProfile;
  fileName: string;
  insights: { text: string; why?: string; confidence: number; tag: string }[];
  story?: string;
  narrative?: string;
}) {
  const { profile, fileName, insights, story, narrative } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  const stripMd = (s: string) => s.replace(/\*\*/g, "").replace(/`/g, "").replace(/^#+\s*/gm, "");

  const writeWrapped = (text: string, size = 11, gap = 4, color?: [number, number, number]) => {
    doc.setFontSize(size);
    if (color) doc.setTextColor(...color);
    const lines = doc.splitTextToSize(stripMd(text), W - M * 2);
    for (const line of lines) {
      if (y > H - M) { doc.addPage(); y = M; }
      doc.text(line, M, y);
      y += size + gap;
    }
    if (color) doc.setTextColor(30, 30, 30);
  };

  const heading = (text: string) => {
    y += 14;
    if (y > H - M - 30) { doc.addPage(); y = M; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(20, 184, 200);
    doc.text(text, M, y);
    // Underline accent
    doc.setDrawColor(20, 184, 200);
    doc.setLineWidth(1.5);
    doc.line(M, y + 4, M + doc.getTextWidth(text), y + 4);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "normal");
    doc.setDrawColor(200, 200, 200);
    y += 20;
  };

  const subHeading = (text: string) => {
    y += 6;
    if (y > H - M - 20) { doc.addPage(); y = M; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 100);
    doc.text(text, M, y);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "normal");
    y += 14;
  };

  // ── Cover block ──
  doc.setFillColor(11, 15, 25);
  doc.rect(0, 0, W, 130, "F");
  // Accent stripe
  doc.setFillColor(20, 184, 200);
  doc.rect(0, 126, W, 4, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Dataset Intelligence Report", M, 55);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(180, 190, 210);
  doc.text(`Generated by AI Dataset Intelligence Engine`, M, 78);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(fileName, M, 100);

  // Trust badge on cover
  const trustColor = profile.trustScore >= 80 ? [16, 185, 129] : profile.trustScore >= 55 ? [245, 158, 11] : [239, 68, 68];
  doc.setFontSize(11);
  doc.setTextColor(180, 190, 210);
  doc.text("Trust Score", W - M - 120, 78);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(trustColor[0], trustColor[1], trustColor[2]);
  doc.text(`${profile.trustScore}`, W - M - 120, 105);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 190, 210);
  doc.text("/100", W - M - 120 + doc.getTextWidth(`${profile.trustScore}`) + 4, 105);

  doc.setTextColor(30, 30, 30);
  y = 160;

  // ── Overview ──
  heading("Overview");
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(M, y - 4, W - M * 2, 36, 4, 4, "F");
  doc.setFontSize(10);
  const stats = [
    `Rows: ${profile.rowCount.toLocaleString()}`,
    `Columns: ${profile.colCount}`,
    `Duplicates: ${profile.duplicateRows}`,
    `Missing: ${profile.missingPct.toFixed(1)}%`,
    `Trust: ${profile.trustScore}/100`,
  ];
  const statWidth = (W - M * 2) / stats.length;
  stats.forEach((s, i) => {
    doc.text(s, M + 8 + i * statWidth, y + 14);
  });
  y += 44;

  // ── Behavior Narrative ──
  if (narrative) { heading("Behavior Narrative"); writeWrapped(narrative); }

  // ── Key Insights ──
  heading("Key Insights");
  for (const i of insights) {
    writeWrapped(`• [${i.tag} · ${(i.confidence * 100).toFixed(0)}%] ${i.text}`);
    if (i.why) writeWrapped(`    Why this matters: ${i.why}`, 10, 3, [100, 100, 120]);
    y += 2;
  }

  // ── Risks ──
  if (profile.risks.length) {
    heading("Risks");
    for (const r of profile.risks) writeWrapped(`• ${r}`);
  }

  // ── Contradictions ──
  if (profile.contradictions.length) {
    heading("Contradictions");
    for (const r of profile.contradictions) writeWrapped(`⚠ ${r}`);
  }

  // ── Human-Error Signals ──
  if (profile.humanErrors.length) {
    heading("Human-Error Signals");
    for (const r of profile.humanErrors) writeWrapped(`⚠ ${r}`);
  }

  // ── Recommended Actions ──
  if (profile.recommendedActions.length) {
    heading("Recommended Actions");
    for (const r of profile.recommendedActions) writeWrapped(`→ ${r}`);
  }

  // ── Column Profile ──
  heading("Column Profile");
  for (const c of profile.columns.slice(0, 30)) {
    writeWrapped(`${c.name}  —  ${c.type}, missing ${c.missingPct.toFixed(1)}%, unique ${c.unique}`, 10, 2);
  }

  // ── Data Story ──
  if (story) { heading("Data Story"); writeWrapped(story); }

  // ── Footer on every page ──
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 170);
    doc.text(`AI Dataset Intelligence Engine — ${fileName}`, M, H - 20);
    doc.text(`Page ${p} of ${pageCount}`, W - M - 60, H - 20);
  }

  doc.save(`${fileName.replace(/\.[^.]+$/, "")}-intelligence-report.pdf`);
}
